<?php
// $Id$
/**
 * @file
 * Hooks and API functions for Data Node module.
 */

/**
 * Implementation of hook_views_api().
 */
function __data_taxonomy_views_api() {
  return array(
    'api' => '2.0',
    'path' => drupal_get_path('module', 'data_taxonomy') .'/views',
  );
}

/**
 * Implementation of hook_menu().
 */
function data_taxonomy_menu() {
  $items = array();
  $items['admin/build/data/edit/%data_ui_table/taxonomy'] = array(
    'title' => 'Relate to taxonomy',
    'description' => 'Administer data tables.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('data_taxonomy_settings_form', 4),
    'file' => 'data_taxonomy.admin.inc',
    'access arguments' => array('administer data tables'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}
